  version: '3.7'

  services:
    web:
      build: .
      command: flask run -h 0.0.0.0 -p 8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - mongo
    mongo:
      image: mongo:4.4.10 # server requirement
      restart: always
